### ISSUE TITLE
Column/Row Header Included in Named Range

### ISSUE THREAD

**Issue by RyanBaileySC** [askvictor/ColumnTools#1]
Hey Victor!

I love the add on! Whenever I create a new named range based on a column or row the title of the named range is listed as the first cell in my selection; however whenever using the newly-created named range as an index, the header cell is included and is throwing off my formulas.

Is there a way to update it to not include the header cell in the named range? 

Desired: NamedRange = Sheet1!A2:A50 when NamedRange is in Sheet1!A1  and selection is Sheet1!A1:A50
vs 
Current: NamedRange = Sheet1!A1:A50 when NamedRange is in Sheet1!A1  and selection is Sheet1!A1:A50

Thank you!

**Comment by askvictor** [comment]
Hi Ryan,

Should be an easy change; I'll have a look at it shortly. Do you think this should be a selectable option, or should it never include the header row (I haven't really used it in the real world, so haven't considered the use cases too much)

**Comment by RyanBaileySC** [comment]
Hey Victor,

Thanks for getting back to me! I greatly appreciate it!

I can’t imagine that it would be too beneficial to have it included as an option. Whenever I create any named range, I normally don’t want to include anything in it beyond the data itself. If I’m using something like INDEX(namedrange1, MATCH(A1,namedrange2,0)) then it would be fine to include the header, but if I did something like COUNTA(namedrange1), then it could include the header in the calculation instead of just the data and throw off another formula.

Also, the “create named range from selection” excel analog doesn’t give you the option to include the header in a newly created named range, but it does give you the option to make named ranges from columns and rows at the same time when you have an array selected.

 It’s a great add on! I use it (and named ranges in general) all the time! It has really helped me in transitioning from excel to sheets for everything.

Thanks again for following up!

**Comment by askvictor** [comment]
Hi Ryan,

I've updated the code, and it should now behave as you requested. It still needs to go through google's approval process, which might take a few hours/days.

**Comment by askvictor** [comment]
Change has been approved by Google; should work as you've requested now :)

**Comment by RyanBaileySC** [comment]
Thank you so much! Excited to use it!
I really appreciate you making the update!

Ryan Bailey
